### ISSUE TITLE
IE11 - Add to cart fail

### ISSUE THREAD

**Issue by Bbahri** [GatsbyStorefront/gatsby-starter-storefront-shopify#4]
While navigatiing on the demo website (https://demo.gatsbystorefront.com/product/copy-of-anchor-bracelet-mega) on IE11, I can't add an item to cart.

### What you did:

I tried to add an item to cart.

When I do a localStorage.getItem('shopify_checkout_id') this return null. So there's not checkoutId set in the local storage, causing the error mentionned above.

### What happened:

I got this error when clicking the button "Add to cart" on a product page in the console:
Unhandled promise rejection Error: [{"message":"Variable $checkoutId of type ID! was provided invalid value","locations":[{"line":1,"column":3229}],"extensions":{"value":"","problems":[{"path":[],"explanation":"Invalid global id ''","message":"Invalid global id ''"}]}}]

### Suggested solution:

I don't have any solution yet.

Do you have any idea how to solve the problem or something to try ?
Thanks !

**Comment by paveli** [comment]
Hi @Bbahri, though Gatsby Storefront may work in IE11 is not made to support it and is not tested with IE. Unfortunately I can not help you with this issue.

You may start debugging from [here](https://github.com/GatsbyStorefront/gatsby-theme-storefront-shopify/blob/08522f55cee0e0c3e639a416ca02e604fdc6af7a/src/hooks/useShopifyFunctions.js#L34) to see if you actually receive a Chackout ID. And maybe rewrite the logic that stores the checkout ID, fix it or maybe use cookies instead of  local storage.

**Comment by Bbahri** [comment]
OK thank you for your quick response. I'll keep you in touch when I'll debug it.
